name: K6 Test on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    env:
      REGION: us-east-1              
      INSTANCE_TYPE: t2.micro       
      K6_SCRIPT: script.js          
      TAG_NAME: k6-test-instance

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Get Latest Amazon Linux AMI
      id: get_ami
      run: |
        AMI_ID=$(aws ec2 describe-images \
          --owners amazon \
          --filters "Name=name,Values=amzn2-ami-hvm-2.0.*-x86_64-gp2" \
          --query 'Images | sort_by(@, &CreationDate)[-1].ImageId' \
          --output text)
        echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

    - name: Create Security Group
      id: create_security_group
      run: |
        SG_ID=$(aws ec2 create-security-group \
          --group-name "k6-test-sg" \
          --description "Security group for K6 test" \
          --vpc-id $(aws ec2 describe-vpcs --query 'Vpcs[0].VpcId' --output text) \
          --query 'GroupId' \
          --output text)
        aws ec2 authorize-security-group-ingress \
          --group-id ${SG_ID} \
          --protocol tcp \
          --port 22 \
          --cidr 0.0.0.0/0
        echo "SECURITY_GROUP=${SG_ID}" >> $GITHUB_ENV

    - name: Get Default Subnet
      id: get_subnet
      run: |
        SUBNET_ID=$(aws ec2 describe-subnets \
          --filters "Name=default-for-az,Values=true" \
          --query 'Subnets[0].SubnetId' \
          --output text)
        echo "SUBNET_ID=${SUBNET_ID}" >> $GITHUB_ENV

    - name: Prepare User Data
      id: prepare_userdata
      run: |
        # Generate the base64-encoded user data script
        USER_DATA=$(cat << EOF
        #!/bin/bash
        sudo yum update -y
        sudo yum install -y docker
        sudo systemctl start docker
        echo "${{ github.workspace }}/scripts/${{ env.K6_SCRIPT }}" > /home/ec2-user/script.js
        sudo docker run -v /home/ec2-user:/scripts --rm grafana/k6 run /scripts/script.js
        EOF
        )
        echo "USER_DATA=${USER_DATA}" >> $GITHUB_ENV

    - name: Launch EC2 Instance
      id: launch_ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ${{ env.AMI_ID }} \
          --count 1 \
          --instance-type ${{ env.INSTANCE_TYPE }} \
          --security-group-ids ${{ env.SECURITY_GROUP }} \
          --subnet-id ${{ env.SUBNET_ID }} \
          --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${{ env.TAG_NAME }}}]" \
          --user-data "$(echo ${{ env.USER_DATA }} | base64)" \
          --query 'Instances[0].InstanceId' \
          --output text)
        echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV

    - name: Wait for Instance to Complete Execution
      run: |
        aws ec2 wait instance-status-ok --instance-ids ${{ env.INSTANCE_ID }}

    - name: Terminate EC2 Instance
      run: |
        aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
        aws ec2 wait instance-terminated --instance-ids ${{ env.INSTANCE_ID }}

    - name: Delete Security Group
      run: |
        aws ec2 delete-security-group --group-id ${{ env.SECURITY_GROUP }}
